### ISSUE TITLE
Compilation error with Linux 6.10 - TBS6904SE

### ISSUE THREAD

**Issue by jansohn** [tbsdtv/linux_media#357]
Here we go again... Starts failing to build with linux kernel 6.10 on my system. 6.9 was working correctly.

    DKMS make.log for tbs_6904_se-6.10 for kernel 6.10.1-arch1-1 (x86_64)
    Fri Jul 26 10:34:35 PM CEST 2024
    make: Entering directory '/var/lib/dkms/tbs_6904_se/6.10/build/media_build'
    make -C linux/ dir DIR="../../media"
    make[1]: Entering directory '/var/lib/dkms/tbs_6904_se/6.10/build/media_build/linux'
    rm -rf drivers include sound mm .patches_applied .linked_dir .git_log.md5 git_log kernel_version.h
    Searching in ../../media/Makefile for kernel version.
    ./use_dir.pl ../../media
    sync file: include/trace/events/vb2.h
    sync file: include/misc/altera.h
    sync file: include/uapi/linux/smiapp.h
    sync file: include/linux/via-core.h
    sync file: include/uapi/linux/media.h
    sync file: include/uapi/linux/v4l2-mediabus.h
    sync file: include/uapi/linux/ivtv.h
    sync file: include/sound/aci.h
    sync file: include/uapi/linux/v4l2-subdev.h
    sync file: include/linux/mmc/sdio_ids.h
    sync file: include/uapi/linux/media-bus-format.h
    sync file: include/linux/ti_wilink_st.h
    sync file: include/uapi/linux/usb/video.h
    sync file: include/linux/dma/xilinx_dma.h
    sync file: include/uapi/linux/cec-funcs.h
    sync file: include/linux/pci_ids.h
    sync file: include/trace/events/pwc.h
    sync file: include/uapi/linux/v4l2-dv-timings.h
    sync file: include/uapi/linux/uvcvideo.h
    sync file: include/linux/atmel-isc-media.h
    sync file: include/uapi/linux/v4l2-common.h
    sync file: include/uapi/linux/v4l2-controls.h
    sync file: include/linux/fixp-arith.h
    sync file: include/trace/events/v4l2.h
    sync file: include/uapi/linux/videodev2.h
    sync file: include/linux/overflow.h
    sync file: sound/pci/bt87x.c
    sync file: include/uapi/linux/xilinx-v4l2-controls.h
    sync file: include/uapi/linux/cec.h
    sync file: include/linux/usb/uvc.h
    sync file: include/uapi/linux/ccs.h
    sync file: include/linux/of_graph.h
    sync file: include/linux/hdmi.h
    sync file: include/uapi/linux/lirc.h
    sync file: include/uapi/linux/max2175.h
    sync file: include/linux/kconfig.h
    sync file: include/uapi/linux/ivtvfb.h
    sync dir: drivers/media/
    sync dir: include/media/
    sync dir: drivers/misc/altera-stapl/
    sync dir: include/dt-bindings/media/
    sync dir: drivers/staging/media/
    sync dir: include/linux/platform_data/media/
    sync dir: include/uapi/linux/dvb/
    make[1]: Leaving directory '/var/lib/dkms/tbs_6904_se/6.10/build/media_build/linux'
    make: Leaving directory '/var/lib/dkms/tbs_6904_se/6.10/build/media_build'
    make: Entering directory '/var/lib/dkms/tbs_6904_se/6.10/build/media_build'
    make -C /var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l
    make[1]: Entering directory '/var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l'
    No version yet, using 6.9.7-arch1-1
    Updating/Creating .config
    make[2]: Entering directory '/var/lib/dkms/tbs_6904_se/6.10/build/media_build/linux'
    Syncing with dir ../../media
    Applying patches for kernel 6.10.1-arch1-1
    patch -s -f -N -p1 -i ../backports/api_version.patch
    patch -s -f -N -p1 -i ../backports/pr_fmt.patch
    patch -s -f -N -p1 -i ../backports/debug.patch
    patch -s -f -N -p1 -i ../backports/drx39xxj.patch
    patch -s -f -N -p1 -i ../backports/ccs.patch
    patch -s -f -N -p1 -i ../backports/rc-cec.patch
    Patched drivers/media/dvb-core/dvbdev.c
    Patched drivers/media/v4l2-core/v4l2-dev.c
    Patched drivers/media/rc/rc-main.c
    Syncing with dir ../../media
    make[2]: Leaving directory '/var/lib/dkms/tbs_6904_se/6.10/build/media_build/linux'
    ./scripts/make_kconfig.pl /lib/modules/6.10.1-arch1-1/build /lib/modules/6.10.1-arch1-1/build
    Preparing to compile for kernel version 6.9.7
    
    ***WARNING:*** You do not have the full kernel sources installed.
    This does not prevent you from building the v4l-dvb tree if you have the
    kernel headers, but the full kernel source may be required in order to use
    make menuconfig / xconfig / qconfig.
    
    If you are experiencing problems building the v4l-dvb tree, please try
    building against a vanilla kernel before reporting a bug.
    
    Vanilla kernels are available at http://kernel.org.
    On most distros, this will compile a newly downloaded kernel:
    
    cp /boot/config-`uname -r` <your kernel dir>/.config
    cd <your kernel dir>
    make all modules_install install
    
    Please see your distro's web site for instructions to build a new kernel.
    
    WARNING: This is the V4L/DVB backport tree, with experimental drivers
             backported to run on legacy kernels from the development tree at:
                    http://git.linuxtv.org/media-tree.git.
             It is generally safe to use it for testing a new driver or
             feature, but its usage on production environments is risky.
             Don't use it in production. You've been warned.
    VIDEO_ROCKCHIP_ISP1: Requires at least kernel 9.255.255
    VIDEO_XILINX: Requires at least kernel 9.255.255
    VIDEO_OV772X: Requires at least kernel 9.255.255
    VIDEO_OV9650: Requires at least kernel 9.255.255
    VIDEO_TC358746: Requires at least kernel 9.255.255
    INTEL_ATOMISP: Requires at least kernel 9.255.255
    VIDEO_IPU3_IMGU: Requires at least kernel 9.255.255
    ./scripts/make_myconfig.pl
    scripts/make_makefile.pl
    [ ! -f "./config-mycompat.h" ] && echo "/* empty config-mycompat.h */" > "./config-mycompat.h" || true
    perl scripts/make_config_compat.pl /lib/modules/6.10.1-arch1-1/build ./.myconfig ./config-compat.h
    creating symbolic links...
    make -C firmware prep
    make[2]: Entering directory '/var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l/firmware'
    make[2]: Nothing to be done for 'prep'.
    make[2]: Leaving directory '/var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l/firmware'
    make -C firmware
    make[2]: Entering directory '/var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l/firmware'
    make[2]: Nothing to be done for 'default'.
    make[2]: Leaving directory '/var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l/firmware'
    Kernel build directory is /lib/modules/6.10.1-arch1-1/build
    make -C ../linux apply_patches
    make[2]: Entering directory '/var/lib/dkms/tbs_6904_se/6.10/build/media_build/linux'
    Syncing with dir ../../media
    Patches for 6.10.1-arch1-1 already applied.
    make[2]: Leaving directory '/var/lib/dkms/tbs_6904_se/6.10/build/media_build/linux'
    make -C /lib/modules/6.10.1-arch1-1/build M=/var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l  modules
    make[2]: Entering directory '/usr/lib/modules/6.10.1-arch1-1/build'
      CC [M]  /var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l/m88rs6000t.o
      CC [M]  /var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l/tuner-simple.o
      CC [M]  /var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l/tuner-types.o
      CC [M]  /var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l/tas2101.o
    /var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l/tas2101.c: In function 'tas2101_attach':
    /var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l/tas2101.c:683:1: warning: label 'err1' defined but not used [-Wunused-label]
      683 | err1:
          | ^~~~
      CC [M]  /var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l/gx1133.o
    /var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l/gx1133.c: In function 'gx1133_attach':
    /var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l/gx1133.c:813:15: error: too many arguments to function 'i2c_mux_add_adapter'
      813 |         ret = i2c_mux_add_adapter(priv->muxc, 0, 0, 0);
          |               ^~~~~~~~~~~~~~~~~~~
    In file included from /var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l/gx1133.c:26:
    ./include/linux/i2c-mux.h:58:5: note: declared here
       58 | int i2c_mux_add_adapter(struct i2c_mux_core *muxc,
          |     ^~~~~~~~~~~~~~~~~~~
    /var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l/gx1133.c:816:15: error: too many arguments to function 'i2c_mux_add_adapter'
      816 |         ret = i2c_mux_add_adapter(priv->muxc, 0, 1, 0);
          |               ^~~~~~~~~~~~~~~~~~~
    ./include/linux/i2c-mux.h:58:5: note: declared here
       58 | int i2c_mux_add_adapter(struct i2c_mux_core *muxc,
          |     ^~~~~~~~~~~~~~~~~~~
    /var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l/gx1133.c: In function 'gx1133_set_frontend':
    /var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l/gx1133.c:1537:9: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
     1537 |         if (ret)
          |         ^~
    /var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l/gx1133.c:1540:17: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
     1540 |                 if (fe->ops.tuner_ops.set_params) {
          |                 ^~
    make[4]: *** [scripts/Makefile.build:244: /var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l/gx1133.o] Error 1
    make[3]: *** [/usr/lib/modules/6.10.1-arch1-1/build/Makefile:1934: /var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l] Error 2
    make[2]: *** [Makefile:240: __sub-make] Error 2
    make[2]: Leaving directory '/usr/lib/modules/6.10.1-arch1-1/build'
    make[1]: *** [Makefile:53: default] Error 2
    make[1]: Leaving directory '/var/lib/dkms/tbs_6904_se/6.10/build/media_build/v4l'
    make: *** [Makefile:26: all] Error 2
    make: Leaving directory '/var/lib/dkms/tbs_6904_se/6.10/build/media_build'

**Comment by TBScardOwner** [comment]
make -C /lib/modules/6.10.2-1-default/build M=/root/media_build/v4l  modules
make[2]: Entering directory '/usr/src/linux-6.10.2-1-obj/x86_64/default'
  LD [M]  /root/media_build/v4l/ccs.o
  LD [M]  /root/media_build/v4l/cx25840.o
  LD [M]  /root/media_build/v4l/et8ek8.o
  LD [M]  /root/media_build/v4l/msp3400.o
  LD [M]  /root/media_build/v4l/s5c73m3.o
  LD [M]  /root/media_build/v4l/tda18271.o
  CC [M]  /root/media_build/v4l/af9013.o
  CC [M]  /root/media_build/v4l/atbm8830.o
  CC [M]  /root/media_build/v4l/au8522_common.o
  CC [M]  /root/media_build/v4l/au8522_dig.o
/root/media_build/v4l/af9013.c: In function 'af9013_probe':
/root/media_build/v4l/af9013.c:1483:15: error: too many arguments to function 'i2c_mux_add_adapter'
 1483 |         ret = i2c_mux_add_adapter(state->muxc, 0, 0, 0);
      |               ^~~~~~~~~~~~~~~~~~~
In file included from /root/media_build/v4l/af9013_priv.h:18,
                 from /root/media_build/v4l/af9013.c:11:
/usr/src/linux-6.10.2-1/include/linux/i2c-mux.h:58:5: note: declared here
   58 | int i2c_mux_add_adapter(struct i2c_mux_core *muxc,
      |     ^~~~~~~~~~~~~~~~~~~
make[4]: *** [/usr/src/linux-6.10.2-1/scripts/Makefile.build:245: /root/media_build/v4l/af9013.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [/usr/src/linux-6.10.2-1/Makefile:1951: /root/media_build/v4l] Error 2
make[2]: *** [../../../linux-6.10.2-1/Makefile:240: __sub-make] Error 2
make[2]: Leaving directory '/usr/src/linux-6.10.2-1-obj/x86_64/default'
make[1]: *** [Makefile:53: default] Error 2
make[1]: Leaving directory '/root/media_build/v4l'
make: *** [Makefile:26: all] Error 2

**Comment by crazycat69** [comment]
[tbsdtv/media_build](https://github.com/tbsdtv/media_build) and [tbsdtv/linux_media](https://github.com/tbsdtv/linux_media) updated for 6.10 compatibility.
Please check

**Comment by TBScardOwner** [comment]
Thank you, works well for me.

**Comment by jansohn** [comment]
Works for me, too. Thanks!
