### ISSUE TITLE
TBS5520 compilation not compile AVL6882 module

### ISSUE THREAD

**Issue by Tnix76** [tbsdtv/linux_media#428]
Hi,

compile TBS5520 tuner in Debian Testing with kernel 7.0.13+deb14-amd64 lacks the AVL6682 module compilation. 

I run the command (as root, explained in https://github.com/tbsdtv/linux_media/wiki):

`curl -sSf https://www.tbsdtv.com/download/document/linux/drv-tbs.sh | sh`

I've reviewed the sources Makefile and I set CONFIG_DVB_AVL6882=m before run ./install.sh

But the next error is throwed:

```
...
frontends/avl6882.c:1466:22: error: redefinition of ‘avl6882_attach’
 1466 | struct dvb_frontend *avl6882_attach(struct avl6882_config *config,
      |                      ^~~~~~~~~~~~~~
In file included from frontends/avl6882.c:31:
frontends/avl6882.h:33:36: note: previous definition of ‘avl6882_attach’ with type ‘struct dvb_frontend *(struct avl6882_config *, struct i2c_adapter *)’
   33 | static inline struct dvb_frontend *avl6882_attach(struct avl6882_config *config,
      |                                    ^~~~~~~~~~~~~~
...
```

With all the TBS5520 module fails with dmesg:

```
DVB: Unable to find symbol avl6882_attach()
TBS5520: frontend attach failed
dvb-usb: no frontend was attached by 'TurboSight TBS 5520 DVB-S/S2/T/T2/C/ISDB-T'
```

Thanks.

**Comment by Davin622** [comment]
sorry for delay reply,
Please add the "CONFIG_DVB_AVL6882=m"  to Makefile.
Downlaod source here:
wget https://www.tbsiptv.com/download/common/tbsdvb_v1013.tar.bz2

and we will update the driver to v1014 for fixed this errors

**Comment by Tnix76** [comment]
> sorry for delay reply, Please add the "CONFIG_DVB_AVL6882=m" to Makefile. Downlaod source here: wget https://www.tbsiptv.com/download/common/tbsdvb_v1013.tar.bz2
> 
> and we will update the driver to v1014 for fixed this errors

Compilation stills fails with the Makefile mod (the same I made before). Next I noted the errors throwed:

```
...
frontends/avl6882.c:1466:22: error: redefinition of ‘avl6882_attach’
 1466 | struct dvb_frontend *avl6882_attach(struct avl6882_config *config,
      |                      ^~~~~~~~~~~~~~
...
make[5]: *** [/usr/src/linux-headers-7.1.3+deb14-common/scripts/Makefile.build:294: frontends/avl6882.o] Error 1
  CC [M]  dvb-usb/tbs5530.o
...
frontends/avl6882.c:1466:22: error: redefinition of ‘avl6882_attach’
 1466 | struct dvb_frontend *avl6882_attach(struct avl6882_config *config,
      |                      ^~~~~~~~~~~~~~
In file included from frontends/avl6882.c:31:
frontends/avl6882.h:33:36: note: previous definition of ‘avl6882_attach’ with type ‘struct dvb_frontend *(struct avl6882_config *, struct i2c_adapter *)’
   33 | static inline struct dvb_frontend *avl6882_attach(struct avl6882_config *config,
      |                                    ^~~~~~~~~~~~~~
...
```

**Comment by Davin622** [comment]
Hello 
the new package(v1014) already upload to website, please running the command again 
curl -sSf https://www.tbsdtv.com/download/document/linux/drv-tbs.sh | sh

**Comment by Tnix76** [comment]
Hello

now the compilation is successful and the TBS5520 works fine with Kaffeine 2.0.18 i.e.

Thank you very much @Davin622 

Regards.
