### ISSUE TITLE
TBS6285 driver not seen with Xbuntu kernel 6.17 - Fixed by using Debian ( TBS 6285 )

### ISSUE THREAD

**Issue by cmcornish** [tbsdtv/linux_media#418]
I'm using a latest clean install of full Xbuntu desktop - LTS 24-04 build. The system is up to date.  I have a TBS6285 card that has been working in the same PC for 10 years. Now having to rebuild the system with a new hard drive. I previously used the closed source drivers with Ubuntu xfce 14.04.

Kernel used is Linux 6.17.0-14-generic #14~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jan 15 15:52:10 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
The TBS6285 card is listed as supported on this wiki page.

I followed the wiki instructions and checked the pre-requisits. With this I get to the "make -j4" command stage and this runs but fails to build. I get the error "media_build/v4l/../linux/include/uapi/linux/videodev2.h:2539:41: error: field 'timestamp' has incomplete type"

I found that the fix for this is to run the command "curl -sSf https://www.tbsdtv.com/download/document/linux/drv-tbs.sh | sh" from other reported issues.
This runs to completion. There are many warnings. I see outputs such as:
Skipping BTF generation for dvb-core/dvb-core.ko due to unavailability of vmlinux
as well as final output of:
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  You are using:           gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
Warning: modules_install: missing 'System.map' file. Skipping depmod.

The card is not seen within the dmesg boot sequence.
Previously, I tried running the command int-1 in saa716x_budget.conf or saa716x_tbs_dvb but these are not recognised.

I can't see and entry for a saa716x driver. Is the card still supported within these latest drivers?
What would you suggest?

Many thanks for your help.

**Comment by cmcornish** [comment]
Hello.
So, it's been an interesting week.
I've discovered that:
- the old version of Mythbuntu is no longer available and the closed source drivers won't compile on Ubuntu 14.04.
- the old Xubuntu versions that are available won't compile the open source drivers.
- these open source drivers do include the saa716x_tbs_dvb drivers
- the wget and curl newer command in the other fixes don't seem to have the saa716x_tbs_dvb driver within it.
- Older versions of other drivers on Github seem to download these latest drivers.

So, I was really stuck. Nothing would get the card to work.

I saw a mention somewhere (can't now find it to give credit) that they were using Debian.
I tried Debian 12 and 13 in XFCE versions, and they both compile these open source drivers (older kernels I think. I suspect that this is the TBS build machine base too). This was a great discovery and solves the issues for me.

I've managed to get the system back up with Debian 13 as the base distribution. The card is seen, and recording now works. I've had to compile Myth-TV from source, but that's easy to do (with a few commands and permission issues to resolve).

I even found some useful Github repositories to make DKMS versions which should be robust through kernel updates. These are @janbar tbs-dvb-driver repository and the one I found most useful being @thecosmicslug TBSDVB_DKMS repository which has easy to follow instructions. Both of these require that the TBS open source drivers compile as they pull the latest code from here.

Issue solved for me for now.

So, to summarise for any others with this card, forget Ubuntu and use Debian instead for the TBS6285 card and Myth-TV.
Check that these drivers compile - they should do so under a Live ISO (but I haven't tried this. I installed it on a spare test drive).

Cheers all.
