### ISSUE TITLE
Failed compilation on Kernel 6.16.0

### ISSUE THREAD

**Issue by alfrup** [tbsdtv/linux_media#411]
As expected: Even with the current kernel 6.16.0, the driver for device TBS6590 cannot be compiled without errors. Error - see below:

creating symbolic links...
perl scripts/make_config_compat.pl /lib/modules/6.16.0-1-default/source ./.myconfig ./config-compat.h
make[2]: Entering directory '/usr/local/sbin/media_build/v4l/firmware'
make[2]: Nothing to be done for 'prep'.
make[2]: Leaving directory '/usr/local/sbin/media_build/v4l/firmware'
make -C firmware
make[2]: Entering directory '/usr/local/sbin/media_build/v4l/firmware'
make[2]: Nothing to be done for 'default'.
make[2]: Leaving directory '/usr/local/sbin/media_build/v4l/firmware'
Kernel build directory is /lib/modules/6.16.0-1-default/build
make -C ../linux apply_patches
make[2]: Entering directory '/usr/local/sbin/media_build/linux'
Syncing with dir ../../media
Patches for 6.16.0-1-default already applied.
make[2]: Leaving directory '/usr/local/sbin/media_build/linux'
make -C /lib/modules/6.16.0-1-default/build M=/usr/local/sbin/media_build/v4l  modules
make[2]: Entering directory '/usr/src/linux-6.16.0-1-obj/x86_64/default'
make[3]: Verzeichnis „/usr/local/sbin/media_build/v4l“ wird betreten
  CC [M]  max2175.o
  CC [M]  ad5820.o
  CC [M]  adp1653.o
  CC [M]  adv7170.o
  CC [M]  adv7175.o
  CC [M]  adv7180.o
  CC [M]  adv7183.o
  CC [M]  adv7343.o
  CC [M]  adv7393.o
  CC [M]  adv7511-v4l2.o
  CC [M]  adv7604.o
  CC [M]  adv7842.o
  CC [M]  ak7375.o
  CC [M]  ak881x.o
  CC [M]  aptina-pll.o
  CC [M]  ar0521.o
  CC [M]  bt819.o
  CC [M]  bt856.o
  CC [M]  bt866.o
  CC [M]  ccs-core.o
  CC [M]  ccs-reg-access.o
  CC [M]  ccs-quirk.o
  CC [M]  ccs-limits.o
  CC [M]  ccs-data.o
  CC [M]  ccs-pll.o
  CC [M]  cs3308.o
  CC [M]  cs5345.o
  CC [M]  cs53l32a.o
  CC [M]  cx25840-core.o
  CC [M]  cx25840-audio.o
In file included from cx25840-audio.c:6:
/usr/local/sbin/media_build/v4l/../linux/include/uapi/linux/videodev2.h:2539:41: error: field 'timestamp' has incomplete type
 2539 |         struct __kernel_timespec        timestamp;
      |                                         ^~~~~~~~~
  CC [M]  cx25840-firmware.o
  CC [M]  cx25840-vbi.o
In file included from cx25840-vbi.c:6:
/usr/local/sbin/media_build/v4l/../linux/include/uapi/linux/videodev2.h:2539:41: error: field 'timestamp' has incomplete type
 2539 |         struct __kernel_timespec        timestamp;
      |                                         ^~~~~~~~~
make[5]: *** [/usr/src/linux-6.16.0-1/scripts/Makefile.build:288: cx25840-audio.o] Fehler 1
make[5]: *** Es wird auf noch nicht beendete Prozesse gewartet …
make[5]: *** [/usr/src/linux-6.16.0-1/scripts/Makefile.build:288: cx25840-vbi.o] Fehler 1
make[4]: *** [/usr/src/linux-6.16.0-1/Makefile:2026: .] Fehler 2
make[3]: *** [/usr/src/linux-6.16.0-1/Makefile:248: __sub-make] Fehler 2
make[3]: Verzeichnis „/usr/local/sbin/media_build/v4l“ wird verlassen
make[2]: *** [../../../linux-6.16.0-1/Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/usr/src/linux-6.16.0-1-obj/x86_64/default'
make[1]: *** [Makefile:53: default] Fehler 2
make[1]: Verzeichnis „/usr/local/sbin/media_build/v4l“ wird verlassen
make: *** [Makefile:26: all] Fehler 2

**Comment by xavan83** [comment]
Same error with kernel 6.17. Do you manage to solve that?

**Comment by d2deco** [comment]
Confirming that I'm also experiencing this error with kernel version 6.17. Had to roll back to 6.14.

**Comment by CvH** [comment]
at 6.17 (proxmox 9.x) still the same error 

```
make -C /lib/modules/6.17.2-2-pve/build M=/root/media_build/v4l  modules
make[2]: Entering directory '/usr/src/linux-headers-6.17.2-2-pve'
make[3]: Entering directory '/root/media_build/v4l'
  LD [M]  ccs.o
  CC [M]  cx25840-audio.o
  CC [M]  cx25840-vbi.o
In file included from cx25840-audio.c:6:
/root/media_build/v4l/../linux/include/uapi/linux/videodev2.h:2539:41: error: field 'timestamp' has incomplete type
 2539 |         struct __kernel_timespec        timestamp;
      |                                         ^~~~~~~~~
  CC [M]  et8ek8_driver.o
In file included from cx25840-vbi.c:6:
/root/media_build/v4l/../linux/include/uapi/linux/videodev2.h:2539:41: error: field 'timestamp' has incomplete type
 2539 |         struct __kernel_timespec        timestamp;
      |                                         ^~~~~~~~~
  CC [M]  hi556.o
make[5]: *** [/usr/src/linux-headers-6.17.2-2-pve/scripts/Makefile.build:287: cx25840-audio.o] Error 1
```

**Comment by xavan83** [comment]
Chatgpt is your friend to fix that one, but you will have plenty others errors after

**Comment by Davin622** [comment]
Hello 
Please try this driver:
https://www.tbsiptv.com/download/common/tbsdvb_v1002.tar.bz2

**Comment by xavan83** [comment]
> Hello Please try this driver: https://www.tbsiptv.com/download/common/tbsdvb_v1002.tar.bz2

Whow! Thank you
It seems to work with my 6.17.0-8-generic ubuntu kernel.
Just uncompressed it and sudo install.sh and it is working
How do you get this file?

**Comment by Davin622** [comment]
Use this command to automatically install or updated the drivers
curl -sSf https://www.tbsdtv.com/download/document/linux/drv-tbs.sh | sh

**Comment by jal-frezie** [comment]
Davin622's driver fails to build on Fedora 43 with Kernel 6.18.5, I get:
``` CC [M]  frontends/dvb-pll.o
frontends/dvb-pll.c: In function ‘dvb_pll_attach’:
frontends/dvb-pll.c:800:14: error: implicit declaration of function ‘ida_simple_get’ [-Wimplicit-function-declaration]
  800 |         nr = ida_simple_get(&pll_ida, 0, DVB_PLL_MAX, GFP_KERNEL);
      |              ^~~~~~~~~~~~~~
frontends/dvb-pll.c:866:9: error: implicit declaration of function ‘ida_simple_remove’ [-Wimplicit-function-declaration]
  866 |         ida_simple_remove(&pll_ida, nr);
      |         ^~~~~~~~~~~~~~~~~
`

**Comment by AndyHarvey99** [comment]
From chatgpt:

Quick fix (recommended)
Replace ida_simple_get() with ida_alloc_range().

Old code (broken)

        nr = ida_simple_get(&pll_ida, 0, DVB_PLL_MAX, GFP_KERNEL);

New code (works on modern kernels)

        nr = ida_alloc_range(&pll_ida, 0, INT_MAX, GFP_KERNEL);

Also check the cleanup path
If you previously had:
        ida_simple_remove(&pll_ida, nr);

Replace with:
        ida_free(&pll_ida, nr);

That worked using tbsdvb_v1002 driver. 
But tbsdvb_v1007 didn't have modules saa716x_tbs_dvb and saa716x_core which I think i need for for my TBS 6982SE DVB-S card.
Note not yet tried with the real hardware on 6.18.5 - only testing on VM without hardware.

v1002 worked on kernel 6.14.11 on my live system.

**Comment by jansohn** [comment]
> Use this command to automatically install or updated the drivers curl -sSf https://www.tbsdtv.com/download/document/linux/drv-tbs.sh | sh

Can we please still get updates in [tbsdtv/media_build](https://github.com/tbsdtv/media_build) and [tbsdtv/linux_media](https://github.com/tbsdtv/linux_media) so we can see what has actually changed and we can continue to use our current setup which has worked for years (for me it is set up to auto-update on every new kernel install via dkms)?

**Comment by Davin622** [comment]
Just using this command to updated on new kernel, It can complete the installation quickly, taking about 2 minutes. This is completely different from before

**Comment by jansohn** [comment]
> Just using this command to updated on new kernel, It can complete the installation quickly, taking about 2 minutes. This is completely different from before

That does not really answer my question. The manual installation does not work for kernels > 6.14 but it is still advertised in the official documentation: https://www.tbsiptv.com/help_center/tbs_driver_installation/linux.html#manual-installation

**Comment by Novgorod** [comment]
> Use this command to automatically install or updated the drivers curl -sSf https://www.tbsdtv.com/download/document/linux/drv-tbs.sh | sh

This does not work on a Proxmox host (6.17.13-1-pve kernel). It builds without errors (but with tons of warnings, which is probably normal), but the kernel module doesn't get loaded, even after a reboot. There are lots of BTF errors like "Skipping BTF generation for frontends/cxd2878.ko due to unavailability of vmlinux" and a depmod error "Warning: modules_install: missing 'System.map' file. Skipping depmod."

The prerequisites such as linux headers for the kernel are all installed. How to fis this?
