### ISSUE TITLE
Unable to compile with kernel 6.19.3-1

### ISSUE THREAD

**Issue by fl0wfr** [tbsdtv/linux_media#421]
Hello,

I tried the drv-tbs.sh install script and I get the following error:

```
frontends/stv6111.c:649:22: error: redefinition of ‘stv6111_attach’
  649 | struct dvb_frontend *stv6111_attach(struct dvb_frontend *fe,
      |                      ^~~~~~~~~~~~~~
In file included from frontends/stv6111.c:17:
frontends/stv6111.h:18:36: note: previous definition of ‘stv6111_attach’ with type ‘struct dvb_frontend *(struct dvb_frontend *, struct i2c_adapter *, u8)’ {aka ‘struct dvb_frontend *(struct dvb_frontend *, struct i2c_adapter *, unsigned char)’}
   18 | static inline struct dvb_frontend *stv6111_attach(struct dvb_frontend *fe,
      |                                    ^~~~~~~~~~~~~~
make[5]: *** [/usr/src/kernels/6.19.3-1.el10.elrepo.x86_64/scripts/Makefile.build:289: frontends/stv6111.o] Error 1
make[4]: *** [/usr/src/kernels/6.19.3-1.el10.elrepo.x86_64/scripts/Makefile.build:546: frontends] Error 2
make[3]: *** [/usr/src/kernels/6.19.3-1.el10.elrepo.x86_64/Makefile:2055: .] Error 2
make[2]: *** [/usr/src/kernels/6.19.3-1.el10.elrepo.x86_64/Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/home/user/tbsdvb'
make[1]: *** [Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/kernels/6.19.3-1.el10.elrepo.x86_64'
make: *** [Makefile:82: all] Error 2
```

I also tried using the git repo but I get the same error as the last created issues.

By the way, it would be nice to catch the error and stop the installer instead of outputting a "V4L drivers installation done" message

**Comment by fl0wfr** [comment]
Solved with Davin (thank you!) after removing CONFIG_DVB_STV6111=m from the Makefile.
