### ISSUE TITLE
TBS6590 device compiling error with kernel 6.5.4

### ISSUE THREAD

**Issue by alfrup** [tbsdtv/linux_media#325]
I need to compile a driver for a TBS6590 device (kernel 6.5.4). When I execute make -j4 I get the following errors:

make -j4
make -C /root/media_build/v4l 
make[1]: Verzeichnis „/root/media_build/v4l“ wird betreten
No version yet, using 6.5.4-1-default
scripts/make_makefile.pl
Updating/Creating .config
make[2]: Entering directory '/root/media_build/linux'
make[2]: Entering directory '/root/media_build/linux'
Syncing with dir ../../media
Syncing with dir ../../media
Applying patches for kernel 6.5.4-1-default
patch -s -f -N -p1 -i ../backports/api_version.patch
patch -s -f -N -p1 -i ../backports/pr_fmt.patch
make[3]: Entering directory '/root/media_build/linux'
Unapplying patches
patch -s -f -R -p1 -i ../backports/api_version.patch
make[3]: Leaving directory '/root/media_build/linux'
Applying patches for kernel 6.5.4-1-default
patch -s -f -N -p1 -i ../backports/api_version.patch
patch -s -f -N -p1 -i ../backports/pr_fmt.patch
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/common/saa7146/saa7146_hlp.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/common/saa7146/saa7146_i2c.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/common/saa7146/saa7146_video.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/common/siano/smscoreapi.h.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/common/tveeprom.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/common/videobuf2/videobuf2-core.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-core/dmxdev.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-core/dvb_ca_en50221.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-core/dvb_demux.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-core/dvb_frontend.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-core/dvb_net.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-core/dvbdev.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-frontends/cxd2880/cxd2880_top.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-frontends/dib0070.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-frontends/dib0090.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-frontends/dib3000mb.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-frontends/dib3000mc.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-frontends/dib7000m.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-frontends/dib7000p.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-frontends/dib8000.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-frontends/dib9000.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-frontends/dibx000_common.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-frontends/drx39xyj/drxj.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-frontends/drxk_hard.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-frontends/dvb-pll.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-frontends/gp8psk-fe.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-frontends/lgdt3306a.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-frontends/nxt200x.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-frontends/nxt6000.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/dvb-frontends/or51211.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/mc/mc-devnode.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/bt8xx/btcx-risc.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/bt8xx/bttv-cards.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/bt8xx/bttv-driver.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/bt8xx/bttv-gpio.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/bt8xx/bttv-i2c.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/bt8xx/bttv-input.c.rej
patch -s -f -N -p1 -i ../backports/debug.patch
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/bt8xx/bttv-risc.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/bt8xx/bttv-vbi.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/bt8xx/dst.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/bt8xx/dvb-bt8xx.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/cx23885/altera-ci.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/cx23885/cx23885.h.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/cx25821/cx25821-alsa.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/cx25821/cx25821-cards.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/cx25821/cx25821-core.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/cx25821/cx25821-i2c.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/cx25821/cx25821-medusa-video.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/cx25821/cx25821-video.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/cx88/cx88.h.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/ddbridge/ddbridge-main.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/ivtv/ivtv-driver.h.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/ngene/ngene-cards.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/saa7134/saa7134.h.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/saa7146/hexium_gemini.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/saa7146/hexium_orion.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/saa7146/mxb.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/pci/ttpci/budget-av.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/platform/samsung/exynos4-is/fimc-is-param.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/platform/samsung/exynos4-is/fimc-is.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/platform/samsung/exynos4-is/fimc-isp.c.rej
patch -s -f -N -p1 -i ../backports/drx39xxj.patch
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/platform/samsung/s3c-camif/camif-capture.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/platform/samsung/s3c-camif/camif-core.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/platform/samsung/s3c-camif/camif-regs.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/rc/ene_ir.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/rc/fintek-cir.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/rc/imon.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/rc/ir-imon-decoder.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/rc/lirc_dev.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/rc/nuvoton-cir.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/rc/rc-main.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/rc/serial_ir.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/rc/winbond-cir.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/spi/cxd2880-spi.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/test-drivers/vidtv/vidtv_common.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/test-drivers/vidtv/vidtv_pes.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/test-drivers/vidtv/vidtv_psi.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/test-drivers/vidtv/vidtv_s302m.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/test-drivers/vidtv/vidtv_ts.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/tuners/r820t.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/tuners/tda18271-priv.h.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/tuners/tea5767.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/au0828/au0828.h.rej
patch -s -f -N -p1 -i ../backports/ccs.patch
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/go7007/go7007-usb.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/benq.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/conex.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/cpia1.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/dtcs033.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/etoms.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/finepix.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/gl860/gl860.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/gspca.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/jeilinj.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/kinect.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/konica.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/m5602/m5602_core.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/m5602/m5602_mt9m111.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/m5602/m5602_ov7660.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/m5602/m5602_ov9650.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/m5602/m5602_po1030.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/m5602/m5602_s5k4aa.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/m5602/m5602_s5k83a.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/mars.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/mr97310a.c.rej
patch -s -f -N -p1 -i ../backports/rc-cec.patch
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/nw80x.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/ov519.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/ov534.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/ov534_9.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/pac207.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/pac7302.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/pac7311.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/se401.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/sn9c2028.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/sn9c20x.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/sonixj.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/spca1528.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/spca500.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/spca501.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/spca505.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/spca508.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/spca561.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/sq905.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/sq905c.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/sq930x.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/stk014.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/stk1135.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/stv0680.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/stv06xx/stv06xx.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/stv06xx/stv06xx_hdcs.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/stv06xx/stv06xx_pb0100.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/stv06xx/stv06xx_st6422.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/stv06xx/stv06xx_vv6410.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/sunplus.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/t613.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/topro.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/vc032x.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/vicam.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/w996Xcf.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/xirlink_cit.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/gspca/zc3xx.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/usb/ttusb-budget/dvb-ttusb-budget.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/v4l2-core/v4l2-ctrls-api.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/v4l2-core/v4l2-ctrls-request.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/media/v4l2-core/v4l2-dev.c.rej
1 out of 1 hunk FAILED -- saving rejects to file drivers/staging/media/av7110/av7110_v4l.c.rej
Patched drivers/media/dvb-core/dvbdev.c
Patched drivers/media/v4l2-core/v4l2-dev.c
Patched drivers/media/rc/rc-main.c
patch -s -f -N -p1 -i ../backports/debug.patch
1 out of 1 hunk FAILED
make[2]: *** [Makefile:135: apply_patches] Error 1
make[2]: Leaving directory '/root/media_build/linux'
Syncing with dir ../../media
make[2]: Leaving directory '/root/media_build/linux'
Preparing to compile for kernel version 6.5.4

***WARNING:*** You do not have the full kernel sources installed.
This does not prevent you from building the v4l-dvb tree if you have the
kernel headers, but the full kernel source may be required in order to use
make menuconfig / xconfig / qconfig.

If you are experiencing problems building the v4l-dvb tree, please try
building against a vanilla kernel before reporting a bug.

Vanilla kernels are available at http://kernel.org.
On most distros, this will compile a newly downloaded kernel:

cp /boot/config-`uname -r` <your kernel dir>/.config
cd <your kernel dir>
make all modules_install install

Please see your distro's web site for instructions to build a new kernel.

WARNING: This is the V4L/DVB backport tree, with experimental drivers
         backported to run on legacy kernels from the development tree at:
                http://git.linuxtv.org/media-tree.git.
         It is generally safe to use it for testing a new driver or
         feature, but its usage on production environments is risky.
         Don't use it in production. You've been warned.
VIDEO_ROCKCHIP_ISP1: Requires at least kernel 9.255.255
VIDEO_XILINX: Requires at least kernel 9.255.255
VIDEO_OV772X: Requires at least kernel 9.255.255
VIDEO_OV9650: Requires at least kernel 9.255.255
VIDEO_TC358746: Requires at least kernel 9.255.255
INTEL_ATOMISP: Requires at least kernel 9.255.255
VIDEO_IPU3_IMGU: Requires at least kernel 9.255.255
Created default (all yes) .config file
./scripts/make_myconfig.pl
scripts/make_makefile.pl
[ ! -f "./config-mycompat.h" ] && echo "/* empty config-mycompat.h */" > "./config-mycompat.h" || true
make -C firmware prep
creating symbolic links...
make[2]: Entering directory '/root/media_build/v4l/firmware'
make[2]: Nothing to be done for 'prep'.
make[2]: Leaving directory '/root/media_build/v4l/firmware'
perl scripts/make_config_compat.pl /lib/modules/6.5.4-1-default/source ./.myconfig ./config-compat.h
make -C firmware
make[2]: Entering directory '/root/media_build/v4l/firmware'
make[2]: Nothing to be done for 'default'.
make[2]: Leaving directory '/root/media_build/v4l/firmware'
Kernel build directory is /lib/modules/6.5.4-1-default/build
make -C ../linux apply_patches
make[2]: Entering directory '/root/media_build/linux'
Syncing with dir ../../media
Patches for 6.5.4-1-default already applied.
make[2]: Leaving directory '/root/media_build/linux'
make -C /lib/modules/6.5.4-1-default/build M=/root/media_build/v4l  modules
make[2]: Entering directory '/usr/src/linux-6.5.4-1-obj/x86_64/default'
  CC [M]  /root/media_build/v4l/max2175.o
  CC [M]  /root/media_build/v4l/ad5820.o
  CC [M]  /root/media_build/v4l/adp1653.o
  CC [M]  /root/media_build/v4l/adv7170.o
In file included from <command-line>:
/root/media_build/v4l/compat.h: In function 'get_user_pages_longterm':
In file included from <command-line>:
/root/media_build/v4l/compat.h: In function 'get_user_pages_longterm':
/root/media_build/v4l/compat.h:673:16: error: too many arguments to function 'get_user_pages'
  673 |         return get_user_pages(start, nr_pages, gup_flags, pages, vmas);
      |                ^~~~~~~~~~~~~~
/root/media_build/v4l/compat.h:673:16: error: too many arguments to function 'get_user_pages'
  673 |         return get_user_pages(start, nr_pages, gup_flags, pages, vmas);
      |                ^~~~~~~~~~~~~~
In file included from /root/media_build/v4l/compat.h:668:
/usr/src/linux-6.5.4-1/include/linux/mm.h:2430:6: note: declared here
 2430 | long get_user_pages(unsigned long start, unsigned long nr_pages,
      |      ^~~~~~~~~~~~~~
In file included from /root/media_build/v4l/compat.h:668:
/usr/src/linux-6.5.4-1/include/linux/mm.h:2430:6: note: declared here
 2430 | long get_user_pages(unsigned long start, unsigned long nr_pages,
      |      ^~~~~~~~~~~~~~
In file included from <command-line>:
/root/media_build/v4l/compat.h: In function 'get_user_pages_longterm':
/root/media_build/v4l/compat.h:673:16: error: too many arguments to function 'get_user_pages'
  673 |         return get_user_pages(start, nr_pages, gup_flags, pages, vmas);
      |                ^~~~~~~~~~~~~~
In file included from /root/media_build/v4l/compat.h:668:
/usr/src/linux-6.5.4-1/include/linux/mm.h:2430:6: note: declared here
 2430 | long get_user_pages(unsigned long start, unsigned long nr_pages,
      |      ^~~~~~~~~~~~~~
In file included from <command-line>:
/root/media_build/v4l/compat.h: In function 'get_user_pages_longterm':
/root/media_build/v4l/compat.h:673:16: error: too many arguments to function 'get_user_pages'
  673 |         return get_user_pages(start, nr_pages, gup_flags, pages, vmas);
      |                ^~~~~~~~~~~~~~
In file included from /root/media_build/v4l/compat.h:668:
/usr/src/linux-6.5.4-1/include/linux/mm.h:2430:6: note: declared here
 2430 | long get_user_pages(unsigned long start, unsigned long nr_pages,
      |      ^~~~~~~~~~~~~~
make[4]: *** [/usr/src/linux-6.5.4-1/scripts/Makefile.build:244: /root/media_build/v4l/ad5820.o] Fehler 1
make[4]: *** Es wird auf noch nicht beendete Prozesse gewartet …
make[4]: *** [/usr/src/linux-6.5.4-1/scripts/Makefile.build:244: /root/media_build/v4l/adp1653.o] Fehler 1
make[4]: *** [/usr/src/linux-6.5.4-1/scripts/Makefile.build:244: /root/media_build/v4l/adv7170.o] Fehler 1
make[4]: *** [/usr/src/linux-6.5.4-1/scripts/Makefile.build:244: /root/media_build/v4l/max2175.o] Fehler 1
make[3]: *** [/usr/src/linux-6.5.4-1/Makefile:2051: /root/media_build/v4l] Fehler 2
make[2]: *** [../../../linux-6.5.4-1/Makefile:234: __sub-make] Error 2
make[2]: Leaving directory '/usr/src/linux-6.5.4-1-obj/x86_64/default'
make[1]: *** [Makefile:53: default] Fehler 2
make[1]: Verzeichnis „/root/media_build/v4l“ wird verlassen
make: *** [Makefile:26: all] Fehler 2

**Comment by crazycat69** [comment]
Look like old media_build
Try latest [tbsdtv/media_build](https://github.com/tbsdtv/media_build) + [tbsdtv/linux_media](https://github.com/tbsdtv/linux_media)

**Comment by miguel1963** [comment]
ok works in kernel 6.5.4 tumbleweed saa 7160 card
