### ISSUE TITLE
upstream new kernel

### ISSUE THREAD

**Issue by bastard79** [tbsdtv/linux_media#303]
is any chance to sync sources with latest linuxtv with support kernel 6.x? or any tutorial how do this by myself?

**Comment by kafisc1** [comment]
Indeed! Would be nice to be able to use kernel 6.1.

**Comment by gpancot** [comment]
i am testing this version for 6.1.12, it seems to work with my tbs6281:
https://github.com/gpancot/linux_media

**Comment by kafisc1** [comment]
Thank's for your feeback.
Not working for me for TBS 6209 on pve-kernel-6.1.10-1-pve.
The error occurs on the step "make":

 CC [M]  /home/tbs_6_1/media_build/v4l/rdacm20.o
/home/tbs_6_1/media_build/v4l/ov7740.c:1217:14: error: initialization of 'void (*)(struct i2c_client *)' from incompatible pointer type 'int (*)(struct i2c_client *)' [-Werror=incompatible-pointer-types]
 1217 |  .remove   = ov7740_remove,

**Comment by gpancot** [comment]
I corrected the error, retry

**Comment by crazycat69** [comment]
Updated, now compatible with 4.14 - 6.2

**Comment by kafisc1** [comment]
> Updated, now compatible with 4.14 - 6.2
Thanks! Working perfectly with Proxmox Kernel 6.2.11-1-pve.
